spring:
  profiles:
    active: dev
  application:
    name: friend-match
# DataSource Config
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/project
    driver-class-name: com.mysql.cj.jdbc.Driver
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
  # redis 配置
  # redis 配置
  redis:
    port: 6379
    host: localhost
    database: 2
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER #swagger配置兼容问题

server:
  port: 8080
  servlet:
    context-path: /api


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false #map-underscore-to-camel-case是将带有下划线的表字段映射为驼峰格式的实体类属性 如果不使用这个配置，需要使用as关键字起别名
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启日志
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

